# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Nextcloud
    url: https://cloud.voit
  - name: Wordpress
    url: https://voit.no
  - name: Disqus
    url: https://prat.voit.no

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.voit.cloud
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/61318223?s=200&v=4
  name: Voit Cloud Services
  introTitle: "**Voit** provides data services to trim down data consumption"
  introMessage: This is the current status of our services.
  navbar:
    - title: Status
      href: /
    - title: Voit
      href: https://voit.no

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
