# Change these first
owner: voitcode # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Nextcloud
    url: https://voit.cloud
  - name: Wordpress
    url: https://voit.no
  - name: Disqus
    url: https://prat.voit.no
  - name: git
    url: https://git.voit.no
  - name: Kuraas webshop
    url: https://kuraas.net

assignees:
  - basso
  - ringe

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.voit.cloud
  baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/61318223?s=200&v=4
  name: Løsninger fra Voit
  introTitle: "**Voit** tilbyr data for mindre data"
  introMessage: Her er status for våre tjenester
  navbar:
    - title: Status
      href: /
    - title: Voit
      href: https://voit.no

i18n:
  activeIncidents: Aktive hendelser
  allSystemsOperational: Alt ser ut for å virke

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
