# Change these first
owner: voitcode # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Nextcloud fra Voit
    url: https://voit.cloud
  - name: Wordpress fra Voit
    url: https://voit.no/wp-login.php
    expectedStatusCodes:
      - 200
      - 201
  - name: Prat med Voit
    url: https://prat.voit.no
  - name: Gitea
    url: https://git.voit.no
  - name: kuraas.no
    url: https://kuraas.no/wp-login.php
    expectedStatusCodes:
      - 200
      - 201
  - name: Kuraas nettbutikk
    url: https://kuraas.net

assignees:
  - basso
  - ringe

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.voit.cloud
  # baseUrl: /upptime
  logoUrl: https://avatars.githubusercontent.com/u/61318223?s=200&v=4
  name: Løsninger fra Voit
  introTitle: "**Voit** tilbyr data for mindre data"
  introMessage: Her er status for våre tjenester
  navbar:
    - title: Status
      href: /
    - title: Voit
      href: https://voit.no

i18n:
  activeIncidents: Aktive hendelser
  allSystemsOperational: Alt er fint!

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
